name: Build and Publish WASM to npm Registry

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          scope: '@visualkey'
      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build WASM package
        run: |
          wasm-pack build --target web --out-dir pkg --scope visualkey
      - name: Publish to npm registry
        run: wasm-pack publish --target web --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}